### ISSUE TITLE
CLI option to disable ANSI formatting

### ISSUE THREAD

**Issue by jmsv** [jmsv/ety-python#31]
PR #29 added bold formatting on input words:

![screenshot from 2018-06-13 09-21-30](https://user-images.githubusercontent.com/14852491/41338881-59ad8de0-6eeb-11e8-8724-32f2a643d839.png)

This is cool :sunglasses: but not always desired, for example when piping to a file:

![screenshot from 2018-06-13 09-53-26](https://user-images.githubusercontent.com/14852491/41340594-a6a5eda0-6eef-11e8-9284-e755d982a130.png)

Flag to disable ANSI could be `-p` (`--plaintext`), e.g.

```python
parser.add_argument("-p", "--plaintext",
                    help="output plaintext, disabling ANSI formatting",
                    action="store_true")
```
---

ANSI codes could be replaced with a library such as [kennethreitz/crayons](https://github.com/kennethreitz/crayons), which supports disabling colours etc. without too much extra code:

```python
if args.plaintext:
    crayons.disable()
```

**Comment by alxwrd** [comment]
I'd suggest [timofurrer/colorful](https://github.com/timofurrer/colorful). It seems to have better windows support.

![the difference between the packages crayons and colorful in a windows environment](https://user-images.githubusercontent.com/13941027/41346841-c432ffc4-6eff-11e8-8dec-d179b07f190d.png)

Also, I think both crayons and colorful disable ANSI when piping.

```shell
$ python -c "import colorful;print(colorful.red('hello'))" > test.txt & cat test.txt
hello
$ python -c "import colorful;print(colorful.red('hello'))" | cat
hello
```

**Comment by alxwrd** [comment]
I think `--plain` could still be useful though, maybe it could turn off the bullet points?

**Comment by parker57** [comment]
Colorful looks cool
Do you think it would be a good idea to assign each language a colour/style?

**Comment by jmsv** [comment]
Probably not, too many languages and not enough style combos

Yeah colorful looks good

`--plain` could make origin lists use `-` instead of bullet points maybe

**Comment by jmsv** [comment]
ANSI replaced with colorful in 583ca75ebc1c388d87b86dc62260af401a66e840
