### ISSUE TITLE
Any word with generic Nahuatl language will raise exception

### ISSUE THREAD

**Issue by gwilken** [jmsv/ety-python#54]
Language code for Nahuatl is missing.

`print(ety.tree('avocado'))`

Will raise an exception:
"Language with iso code 'nah' unknown"

ISO 639 specifies it:
[https://en.wikipedia.org/wiki/Template:ISO_639_name_nah](https://en.wikipedia.org/wiki/Template:ISO_639_name_nah)

Recommend adding it to data/iso-639-3.json

btw thank you! awesome work!

**Comment by jmsv** [comment]
Ah, well spotted! Looks like ety uses an incomplete ISO 639-3 dataset.

Will looking into swapping it out for a different one soon, otherwise will just add it to the existing ISO 639-3 data.

**Comment by jmsv** [comment]
fixed in v1.3.2 🎉
