### ISSUE TITLE
Any word with Wintu language will raise exception

### ISSUE THREAD

**Issue by gwilken** [jmsv/ety-python#55]
`print(ety.tree('Wintun'))`

Will throw an exception:
"Language with iso code 'wit' unknown"

'wit' seems to be deprecated in ISO 639-3 in favor of 'wnw', but alas, it still exists in the data.

[https://iso639-3.sil.org/code/wit](https://iso639-3.sil.org/code/wit)
[https://iso639-3.sil.org/code/wnw](https://iso639-3.sil.org/code/wnw)

**Comment by jmsv** [comment]
Hmm ety's [dataset](http://www1.icsi.berkeley.edu/~demelo/etymwn/) claims to use ISO 639-3 language codes — might be that there are a few erroneous 639-1/2 codes. Will look into this later.

Thanks for reporting this! :fire:

**Comment by jmsv** [comment]
updating [data generation script](https://github.com/jmsv/ety-python/blob/master/ety/data/generate.py) to replace `wit` codes with `wnw`

**Comment by jmsv** [comment]
fixed in v1.3.3 :fire:
